// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/award_offline": {
            "post": {
                "description": "AwardOffLine",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "离线收益",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamAwardVideoResp"
                        }
                    }
                }
            }
        },
        "/award_video": {
            "post": {
                "description": "AwardVideo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "看视频奖励",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamAwardVideo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamAwardVideoResp"
                        }
                    }
                }
            }
        },
        "/award_watch": {
            "post": {
                "description": "AwardWatch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "【商业化模块】看视频领金币",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamAwardVideoResp"
                        }
                    }
                }
            }
        },
        "/daily": {
            "post": {
                "description": "Daily",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "近 5 天天气信息",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWeatherInfo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helper.DailyStyle"
                            }
                        }
                    }
                }
            }
        },
        "/hourly": {
            "post": {
                "description": "Hourly",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "近 24 小时 天气信息",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWeatherInfo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helper.DailyStyle"
                            }
                        }
                    }
                }
            }
        },
        "/incentive_100_redpack_entrance": {
            "post": {
                "description": "Incentive100Entrance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "百元红包入口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/xconfig.IncentiveEntranceResp"
                        }
                    }
                }
            }
        },
        "/incentive_100_redpack_info": {
            "post": {
                "description": "Incentive100Info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "百元红包",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/xconfig.IncentiveInfoResp"
                        }
                    }
                }
            }
        },
        "/incentive_100_update_progress": {
            "post": {
                "description": "Incentive100UpdateProgress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "百元红包 更新进度+1",
                "responses": {
                    "200": {}
                }
            }
        },
        "/info": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "旧版兼容 彩云api",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWeatherInfo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWeatherInfoResp"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "上传登录",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamLogin"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamLoginResp"
                        }
                    }
                }
            }
        },
        "/lucky_draw_do_millstone": {
            "post": {
                "description": "CashWheelMillstone",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "现金大转盘"
                ],
                "summary": "大转盘领取累计奖励",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamMillstone"
                        }
                    }
                ]
            }
        },
        "/lucky_draw_do_redpack": {
            "post": {
                "description": "CashWheelOpenRedPacket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "现金大转盘"
                ],
                "summary": "大转盘领取开到的红包",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamOpenRedPacket"
                        }
                    }
                ]
            }
        },
        "/lucky_draw_info": {
            "post": {
                "description": "CashWheelInfo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "现金大转盘"
                ],
                "summary": "大转盘信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ]
            }
        },
        "/lucky_draw_play": {
            "post": {
                "description": "CashWheelPlay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "现金大转盘"
                ],
                "summary": "大转盘抽奖",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamStatisticIncentive"
                        }
                    }
                ]
            }
        },
        "/new_user_gift_info": {
            "post": {
                "description": "UserGiftInfo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "新人礼信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamUserGiftInfoResp"
                        }
                    }
                }
            }
        },
        "/new_user_gift_reward": {
            "post": {
                "description": "UserGiftInfo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "新人礼信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamUserGiftInfoResp"
                        }
                    }
                }
            }
        },
        "/now_time": {
            "post": {
                "description": "NowTime",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "当天天气信息",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWeatherInfo"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.RealTime"
                        }
                    }
                }
            }
        },
        "/sign_info": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "SignInfo 签到信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/statistic_action": {
            "post": {
                "description": "StatisticAction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "设备验证信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamStatisticAction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamStatisticAction"
                        }
                    }
                }
            }
        },
        "/statistic_incentive_incr": {
            "post": {
                "description": "StatisticIncentiveIncr",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "百元红包",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamStatisticIncentive"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/xconfig.IncentiveInfoResp"
                        }
                    }
                }
            }
        },
        "/warm_remind": {
            "post": {
                "description": "WarmRemind",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "天气面板"
                ],
                "summary": "温度提醒",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWarmRemindResp"
                        }
                    }
                }
            }
        },
        "/withdraw_deal": {
            "post": {
                "description": "发起提现，下单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web提现页面"
                ],
                "summary": "发起提现",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWithdrawDeal"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.WithdrawInnerOrderDealResponse"
                        }
                    }
                }
            }
        },
        "/withdraw_info": {
            "post": {
                "description": "提现信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web提现页面"
                ],
                "summary": "提现信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.WithdrawInnerOrderDealResponse"
                        }
                    }
                }
            }
        },
        "/withdraw_orders": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web提现页面"
                ],
                "summary": "提现记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helper.WithdrawInnerOrderResponse"
                            }
                        }
                    }
                }
            }
        },
        "/wx/auth_code/decrypt": {
            "post": {
                "description": "authCode 换 openId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "web提现页面"
                ],
                "summary": "authCode 换 openId",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamCode2OpenId"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.AuthCodeResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helper.AuthCodeResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "openid": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "scope": {
                    "type": "string"
                },
                "unionid": {
                    "type": "string"
                }
            }
        },
        "helper.DailyStyle": {
            "type": "object",
            "properties": {
                "aqi": {
                    "type": "number"
                },
                "date": {
                    "type": "integer"
                },
                "skycon": {
                    "type": "string"
                },
                "sunrise": {
                    "type": "string"
                },
                "sunset": {
                    "type": "string"
                },
                "temperature_max": {
                    "type": "string"
                },
                "temperature_min": {
                    "type": "string"
                }
            }
        },
        "helper.HourlyStyle": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "integer"
                },
                "skycon": {
                    "type": "string"
                },
                "temperature": {
                    "type": "string"
                }
            }
        },
        "helper.LifeSuggestion": {
            "type": "object",
            "properties": {
                "airing": {
                    "description": "晾晒",
                    "type": "string"
                },
                "dressing": {
                    "description": "Dating    string ` + "`" + `json:\"dating\"` + "`" + `    // 约会指数",
                    "type": "string"
                },
                "fishing": {
                    "description": "钓鱼指数",
                    "type": "string"
                },
                "flu": {
                    "description": "感冒指数",
                    "type": "string"
                },
                "sport": {
                    "description": "运动指数",
                    "type": "string"
                },
                "sunscreen": {
                    "description": "防晒指数",
                    "type": "string"
                },
                "travel": {
                    "description": "旅游指数",
                    "type": "string"
                },
                "uv": {
                    "description": "紫外线指数",
                    "type": "string"
                }
            }
        },
        "helper.ParamAwardVideo": {
            "type": "object",
            "properties": {
                "award_name": {
                    "description": "奖励类型 (兼容老版本新字段)",
                    "type": "string"
                },
                "award_type": {
                    "description": "奖励类型 1 温差 2 倒计时 3 任务 4签到 5新人红包",
                    "type": "integer"
                },
                "base_coin": {
                    "description": "原来奖励金币数量",
                    "type": "integer"
                },
                "multiple": {
                    "description": "倍数",
                    "type": "integer"
                },
                "uid": {
                    "description": "用户 id",
                    "type": "integer"
                }
            }
        },
        "helper.ParamAwardVideoResp": {
            "type": "object",
            "properties": {
                "award_coins": {
                    "type": "integer"
                },
                "had_cash": {
                    "type": "string"
                },
                "had_coin": {
                    "type": "integer"
                },
                "is_award_watch_times": {
                    "type": "boolean"
                }
            }
        },
        "helper.ParamCode2OpenId": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "authcode 码",
                    "type": "string"
                },
                "source": {
                    "description": "可选参数",
                    "type": "string"
                }
            }
        },
        "helper.ParamLogin": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号名称",
                    "type": "string"
                },
                "login_type": {
                    "description": "1 手机 2 微信",
                    "type": "integer"
                },
                "uid": {
                    "description": "用户 id",
                    "type": "integer"
                }
            }
        },
        "helper.ParamLoginResp": {
            "type": "object",
            "properties": {
                "is_withdrew_03": {
                    "description": "是否提现过",
                    "type": "boolean"
                },
                "open_id": {
                    "description": "微信 openid",
                    "type": "string"
                },
                "user_info": {
                    "type": "object"
                }
            }
        },
        "helper.ParamMillstone": {
            "type": "object",
            "properties": {
                "millstone_id": {
                    "type": "integer"
                }
            }
        },
        "helper.ParamOpenRedPacket": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "helper.ParamStatisticAction": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "登录状态 已登录：\"login\" 未登录 \"notlogin\"",
                    "type": "string"
                }
            }
        },
        "helper.ParamStatisticIncentive": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "times": {
                    "type": "integer"
                },
                "tu": {
                    "type": "string"
                }
            }
        },
        "helper.ParamUserGiftInfoResp": {
            "type": "object",
            "properties": {
                "can_reward": {
                    "description": "是否可以领取",
                    "type": "boolean"
                },
                "cash": {
                    "description": "奖励额度",
                    "type": "string"
                },
                "had_cash": {
                    "type": "string"
                },
                "had_coin": {
                    "type": "integer"
                },
                "reward_cash": {
                    "description": "奖励数额",
                    "type": "integer"
                }
            }
        },
        "helper.ParamWarmRemindResp": {
            "type": "object",
            "properties": {
                "notice": {
                    "description": "提醒",
                    "type": "string"
                }
            }
        },
        "helper.ParamWeatherInfo": {
            "type": "object",
            "properties": {
                "city_code": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "TestGroup": {
                    "description": "实验组",
                    "type": "string"
                },
                "time": {
                    "description": "客户端访问时间",
                    "type": "string"
                },
                "uid": {
                    "type": "integer"
                },
                "weatherType": {
                    "description": "查看天气的类型",
                    "type": "string"
                }
            }
        },
        "helper.ParamWeatherInfoResp": {
            "type": "object",
            "properties": {
                "daily": {
                    "description": "日数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helper.DailyStyle"
                    }
                },
                "hourly": {
                    "description": "小时数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helper.HourlyStyle"
                    }
                },
                "realtime": {
                    "description": "当前信息",
                    "type": "object",
                    "$ref": "#/definitions/helper.RealTime"
                }
            }
        },
        "helper.ParamWithdrawDeal": {
            "type": "object",
            "properties": {
                "bank": {
                    "description": "银行",
                    "type": "string"
                },
                "bank_account": {
                    "description": "账户",
                    "type": "string"
                },
                "device": {
                    "type": "object",
                    "properties": {
                        "is_emulator": {
                            "description": "手机设备",
                            "type": "boolean"
                        },
                        "is_root": {
                            "description": "手机设备",
                            "type": "boolean"
                        },
                        "is_xposed_exist": {
                            "description": "手机设备",
                            "type": "boolean"
                        }
                    }
                },
                "goods_id": {
                    "description": "商品 id",
                    "type": "integer"
                },
                "id_card": {
                    "description": "银行卡",
                    "type": "string"
                },
                "name": {
                    "description": "商品名称",
                    "type": "string"
                },
                "phone": {
                    "description": "下单手机号",
                    "type": "string"
                }
            }
        },
        "helper.RealTime": {
            "type": "object",
            "properties": {
                "alert_desc": {
                    "description": "预警详细文字描述",
                    "type": "string"
                },
                "date": {
                    "type": "integer"
                },
                "forecast_keypoint": {
                    "description": "生活指数预报的详细描述，可能为空",
                    "type": "string"
                },
                "humidity": {
                    "description": "湿度",
                    "type": "string"
                },
                "life_suggestion": {
                    "description": "Comfort          string ` + "`" + `json:\"comfort\"` + "`" + `           // 舒适指数",
                    "type": "object",
                    "$ref": "#/definitions/helper.LifeSuggestion"
                },
                "warm_remind": {
                    "description": "提示",
                    "type": "string"
                }
            }
        },
        "helper.WithdrawGoods": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "价格",
                    "type": "integer"
                },
                "bank": {
                    "description": "支付方式",
                    "type": "string"
                },
                "cash_type": {
                    "description": "0 ：48 小时到账 ； 1 实时到账",
                    "type": "integer"
                },
                "current_day_withdraw_num": {
                    "description": "当日提现次数",
                    "type": "integer"
                },
                "current_withdraw_num": {
                    "description": "当前提现次数",
                    "type": "integer"
                },
                "day_max_withdraw_num": {
                    "description": "单日提现次数",
                    "type": "integer"
                },
                "goods_id": {
                    "description": "商品 id",
                    "type": "integer"
                },
                "goods_type": {
                    "description": "商品性质 一次性 多次",
                    "type": "string"
                },
                "group": {
                    "type": "integer"
                },
                "max_withdraw_num": {
                    "description": "最大提现次数",
                    "type": "integer"
                },
                "show": {
                    "description": "是否页面展示",
                    "type": "boolean"
                },
                "ticket_num": {
                    "description": "现金券数量",
                    "type": "integer"
                }
            }
        },
        "helper.WithdrawInnerOrderDealData": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "数额",
                    "type": "integer"
                },
                "goods": {
                    "description": "商品",
                    "type": "object",
                    "$ref": "#/definitions/helper.WithdrawGoods"
                },
                "is_first": {
                    "description": "是否第一次提现 1 否 2 是",
                    "type": "integer"
                },
                "order": {
                    "type": "object",
                    "properties": {
                        "order_id": {
                            "description": "订单 id",
                            "type": "integer"
                        },
                        "order_no": {
                            "description": "订单号",
                            "type": "string"
                        }
                    }
                },
                "ticket_num": {
                    "description": "现金券",
                    "type": "integer"
                }
            }
        },
        "helper.WithdrawInnerOrderDealResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/helper.WithdrawInnerOrderDealData"
                },
                "error_code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "time_unix": {
                    "type": "integer"
                }
            }
        },
        "helper.WithdrawInnerOrderResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "amount": {
                                "description": "金额",
                                "type": "integer"
                            },
                            "app_name": {
                                "description": "app 名称",
                                "type": "string"
                            },
                            "bank": {
                                "description": "提现方式",
                                "type": "string"
                            },
                            "bank_account": {
                                "description": "提现账户",
                                "type": "string"
                            },
                            "comment": {
                                "description": "内容",
                                "type": "string"
                            },
                            "created_at": {
                                "type": "string"
                            },
                            "goods_type": {
                                "description": "类型",
                                "type": "string"
                            },
                            "id": {
                                "description": "订单 id",
                                "type": "integer"
                            },
                            "id_card": {
                                "description": "卡号",
                                "type": "string"
                            },
                            "name": {
                                "description": "账户名称",
                                "type": "string"
                            },
                            "order_no": {
                                "description": "订单号",
                                "type": "string"
                            },
                            "phone": {
                                "description": "手机号",
                                "type": "string"
                            },
                            "status": {
                                "description": "状态",
                                "type": "integer"
                            },
                            "tickets": {
                                "description": "券",
                                "type": "string"
                            },
                            "uid": {
                                "description": "用户id",
                                "type": "integer"
                            },
                            "updated_at": {
                                "type": "string"
                            }
                        }
                    }
                },
                "error_code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "time_unix": {
                    "type": "integer"
                }
            }
        },
        "xconfig.Incentive100Group": {
            "type": "object",
            "properties": {
                "head_img": {
                    "type": "string"
                },
                "me": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                }
            }
        },
        "xconfig.Incentive100Notice": {
            "type": "object",
            "properties": {
                "head_img": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "xconfig.IncentiveEntranceResp": {
            "type": "object",
            "properties": {
                "enable": {
                    "type": "boolean"
                },
                "expire_time": {
                    "type": "integer"
                },
                "notice": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xconfig.Incentive100Notice"
                    }
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "xconfig.IncentiveInfoResp": {
            "type": "object",
            "properties": {
                "day_num": {
                    "type": "integer"
                },
                "expire_time": {
                    "type": "integer"
                },
                "group_rank": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xconfig.Incentive100Group"
                    }
                },
                "has_rewarded": {
                    "type": "boolean"
                },
                "last_update_ts": {
                    "type": "integer"
                },
                "max_progress": {
                    "type": "integer"
                },
                "notice": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/xconfig.Incentive100Notice"
                    }
                },
                "period": {
                    "type": "string"
                },
                "progress": {
                    "type": "integer"
                },
                "toast": {
                    "type": "string"
                },
                "today_remain": {
                    "type": "integer"
                },
                "today_time": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "pgd-beta.cootekservice.com",
	BasePath:    "/a/weather/",
	Schemes:     []string{},
	Title:       "天气实况 API",
	Description: "This is a base annotation server celler server.\n解放双手不再手写 api ，基于注释生成文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
