// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mig/pig/benefit/daily_bag/collect": {
            "post": {
                "description": "DailyBagBenefitInfoCollect",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "领取福利球任务",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamDailyBagCollect"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helper.EnergyRewardRecord"
                            }
                        }
                    }
                }
            }
        },
        "/mig/pig/benefit/daily_bag/info": {
            "post": {
                "description": "DailyBagBenefitInfoGet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "获取福利球任务信息",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamGroup"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helper.BallInfoResp"
                            }
                        }
                    }
                }
            }
        },
        "/mig/pig/task/task_do": {
            "post": {
                "description": "TaskDo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "做福利任务",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamWithdrawBeanTask"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamDoTaskResp"
                        }
                    }
                }
            }
        },
        "/mig/pig/task/task_list": {
            "post": {
                "description": "TaskList",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商业化"
                ],
                "summary": "获取任务中心",
                "parameters": [
                    {
                        "description": "必填参数",
                        "name": "请求体",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/helper.ParamTaskGet"
                        }
                    },
                    {
                        "type": "string",
                        "description": "校验 Auth-Token ",
                        "name": "Auth-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/helper.ParamTaskListResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "helper.BallInfo": {
            "type": "object",
            "properties": {
                "count_down": {
                    "description": "CD时间",
                    "type": "integer"
                },
                "id": {
                    "description": "福利球 id",
                    "type": "string"
                },
                "incentive_reward": {
                    "type": "integer"
                },
                "max_times": {
                    "description": "最大次数",
                    "type": "integer"
                },
                "remaining_times": {
                    "type": "integer"
                },
                "reward": {
                    "description": "奖励数额",
                    "type": "integer"
                }
            }
        },
        "helper.BallInfoResp": {
            "type": "object",
            "properties": {
                "rewards": {
                    "description": "福利球信息 数组",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helper.BallInfo"
                    }
                }
            }
        },
        "helper.EnergyRewardRecord": {
            "type": "object",
            "properties": {
                "reward_amount": {
                    "description": "奖励数量",
                    "type": "integer"
                },
                "reward_id": {
                    "description": "奖励 id",
                    "type": "string"
                },
                "reward_type": {
                    "description": "奖励类型",
                    "type": "string"
                }
            }
        },
        "helper.FreeTask": {
            "type": "object",
            "properties": {
                "action_key": {
                    "type": "string"
                },
                "award_num": {
                    "description": "奖励数额",
                    "type": "integer"
                },
                "award_type": {
                    "description": "奖励类型 用于记录发金币 label",
                    "type": "string"
                },
                "button": {
                    "description": "按钮文案",
                    "type": "string"
                },
                "count_down": {
                    "description": "任务领取间隔倒计时",
                    "type": "integer"
                },
                "current_num": {
                    "description": "当前已做次数",
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "enable": {
                    "description": "是否开启任务",
                    "type": "boolean"
                },
                "max_num": {
                    "description": "最大次数",
                    "type": "integer"
                },
                "max_time": {
                    "type": "integer"
                },
                "min_app_version": {
                    "type": "integer"
                },
                "need_reaching_target": {
                    "type": "boolean"
                },
                "progress": {
                    "description": "进度",
                    "type": "integer"
                },
                "reward": {
                    "type": "integer"
                },
                "status": {
                    "description": "1待完成 2待领取 3已完成",
                    "type": "integer"
                },
                "tag": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "target": {
                    "type": "integer"
                },
                "task_id": {
                    "description": "任务唯一表示 ids",
                    "type": "string"
                },
                "task_type": {
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "type": {
                    "description": "任务类型",
                    "type": "string"
                },
                "weight": {
                    "description": "排序权重 从大到小",
                    "type": "integer"
                }
            }
        },
        "helper.ParamDailyBagCollect": {
            "type": "object",
            "properties": {
                "group": {
                    "description": "初版不用传",
                    "type": "string"
                },
                "id": {
                    "description": "福利球 id",
                    "type": "string"
                },
                "incentive": {
                    "description": "初版不用传",
                    "type": "boolean"
                }
            }
        },
        "helper.ParamDoTaskResp": {
            "type": "object",
            "properties": {
                "award_coins": {
                    "description": "奖励数额",
                    "type": "integer"
                },
                "is_award_watch_times": {
                    "type": "boolean"
                },
                "is_guide": {
                    "description": "判断是否跳引导页面",
                    "type": "boolean"
                }
            }
        },
        "helper.ParamGroup": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                }
            }
        },
        "helper.ParamTaskGet": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "string"
                },
                "task_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "helper.ParamTaskListResp": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/helper.FreeTask"
                    }
                }
            }
        },
        "helper.ParamWithdrawBeanTask": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "dev[pgd-beta.cootekservice.com]  prod[pig.chubaobaitiao.com]",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "财生小猪 API",
	Description: "This is a base annotation server celler server.\n解放双手不再手写 api ，基于注释生成文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
