package main

import "runtime"

// 大于2m 结构体
type BigBar struct {
	foo runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
}
