package main

import "runtime"

type Buiding interface {
	Builds()
}

type House struct {
}

func (House) Builds() {
	println("House")
}

type Shop struct {
}

func (Shop) Builds() {
	println("Shop")
}

type Toilet struct {
}

func (Toilet) Builds() {
	println("Toilet")
}

// 大于2m 结构体
type BigBar struct {
	foo runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
	_   runtime.MemStats
}
